<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitle ?? 'AnimaMarket' ?></title>
    
    <!-- CSS BASE -->
    <link rel="stylesheet" href="<?= BASE_URL ?>css/main.css">

</head>
<body>
    <?php require_once __DIR__ . '/../partials/header.phtml'; ?>
    
    <div class="site-main"> 
        <?= $content ?>
    </div>

    <?php require_once __DIR__ . '/../partials/footer.phtml'; ?>

    <!-- JS PRINCIPAL -->
    <script src="<?= BASE_URL ?>js/main.js"></script>
</body>
</html>